// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"iztro/Izplace/palace.type":{"path":"iztro/Izplace/palace/type","id":"iztro/Izplace/palace.type","parentId":"@@/global-layout"},"iztro/Izcenter/index":{"path":"iztro/Izcenter","id":"iztro/Izcenter/index","parentId":"@@/global-layout"},"iztro/Izcenter/item":{"path":"iztro/Izcenter/item","id":"iztro/Izcenter/item","parentId":"@@/global-layout"},"iztro/Izcenter/line":{"path":"iztro/Izcenter/line","id":"iztro/Izcenter/line","parentId":"@@/global-layout"},"iztro/Izplace/index":{"path":"iztro/Izplace","id":"iztro/Izplace/index","parentId":"@@/global-layout"},"basic/AddHostModal":{"path":"basic/AddHostModal","id":"basic/AddHostModal","parentId":"@@/global-layout"},"iztro/Izstar/index":{"path":"iztro/Izstar","id":"iztro/Izstar/index","parentId":"@@/global-layout"},"analyze/starsDesc":{"path":"analyze/starsDesc","id":"analyze/starsDesc","parentId":"@@/global-layout"},"analyze/index":{"path":"analyze","id":"analyze/index","parentId":"@@/global-layout"},"iztro/Iztro":{"path":"iztro/Iztro","id":"iztro/Iztro","parentId":"@@/global-layout"},"index":{"path":"/","id":"index","parentId":"@@/global-layout"},"docs":{"path":"docs","id":"docs","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'iztro/Izplace/palace.type': React.lazy(() => import(/* webpackChunkName: "src__pages__iztro__Izplace__palace.type" */'../../../src/pages/iztro/Izplace/palace.type.ts')),
'iztro/Izcenter/index': React.lazy(() => import(/* webpackChunkName: "src__pages__iztro__Izcenter__index" */'../../../src/pages/iztro/Izcenter/index.tsx')),
'iztro/Izcenter/item': React.lazy(() => import(/* webpackChunkName: "src__pages__iztro__Izcenter__item" */'../../../src/pages/iztro/Izcenter/item.tsx')),
'iztro/Izcenter/line': React.lazy(() => import(/* webpackChunkName: "src__pages__iztro__Izcenter__line" */'../../../src/pages/iztro/Izcenter/line.tsx')),
'iztro/Izplace/index': React.lazy(() => import(/* webpackChunkName: "src__pages__iztro__Izplace__index" */'../../../src/pages/iztro/Izplace/index.tsx')),
'basic/AddHostModal': React.lazy(() => import(/* webpackChunkName: "src__pages__basic__AddHostModal" */'../../../src/pages/basic/AddHostModal.tsx')),
'iztro/Izstar/index': React.lazy(() => import(/* webpackChunkName: "src__pages__iztro__Izstar__index" */'../../../src/pages/iztro/Izstar/index.tsx')),
'analyze/starsDesc': React.lazy(() => import(/* webpackChunkName: "src__pages__analyze__starsDesc" */'../../../src/pages/analyze/starsDesc.js')),
'analyze/index': React.lazy(() => import(/* webpackChunkName: "src__pages__analyze__index" */'../../../src/pages/analyze/index.tsx')),
'iztro/Iztro': React.lazy(() => import(/* webpackChunkName: "src__pages__iztro__Iztro" */'../../../src/pages/iztro/Iztro.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'docs': React.lazy(() => import(/* webpackChunkName: "src__pages__docs" */'../../../src/pages/docs.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/wvvw/fun/zwds/zw/src/layouts/index.tsx')),
},
  };
}
